routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/



Route::post('users/register-user', 'UserController@registerUser')->name('users.register');
Route::resource('users', 'UserController');

Route::delete('/categories/{categories}/permanent', 'CategoryController@permanentDelete')->name('categories.permanent');
Route::get('/categories/{categories}/restore', 'CategoryController@restore')->name('categories.restore');
Route::get('/categories/trash', 'CategoryController@trash')->name('categories.trash');
Route::resource('categories', 'CategoryController');

Route::get('/', 'BookController@homePages');
Route::delete('/books/{books}/permanent', 'BookController@permanentDelete')->name('books.permanent');
Route::get('/books/{books}/restore', 'BookController@restore')->name('books.restore');
Route::get('/books/trash', 'BookController@trash')->name('books.trash');
Route::get('/books/draft', 'BookController@draft')->name('books.draft');
Route::put('/books/order/{books}', 'BookController@order')->name('books.order');
Route::resource('books', 'BookController');

Route::delete('/orders/{orders}/permanent', 'OrderController@permanentDelete')->name('orders.permanent');
Route::get('/orders/{orders}/restore', 'OrderController@restore')->name('orders.restore');
Route::get('/orders/trash', 'OrderController@trash')->name('orders.trash');
Route::resource('orders', 'OrderController');
Auth::routes();
Route::get('/home', 'HomeController@index')->name('home');

app/Models/Book.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use App\Models\Category;
use App\Models\Order;

class Book extends Model
{
    use SoftDeletes;

    protected $guarded = [];

    public function categories()
    {
        return $this->belongsToMany(Category::class);
    }

    public function orders()
    {
        return $this->belongsToMany(Order::class);
    }
}

app/Http/Controllers/BookController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Book;
use App\Models\Category;
use App\Models\Order;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\File;
use Illuminate\Support\Facades\Gate;
use Illuminate\Support\Str;

class BookController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function __construct()
    {
        $this->middleware(function ($request, $next) {
            if (Gate::allows('manage-books')) {
                return $next($request);
            }
            abort(403, 'Anda tidak memiliki akses untuk mengakses halaman ini');
        })->except('homePages');
    }
    public function index(Request $request)
    {
        $books = Book::all();
        $categories = Category::all();
        if ($request->title) {
            $books = Book::where('title', 'like', "%$request->title%")->get();
        }
        if ($request->status) {
            $books = Book::where('status', strtoupper($request->status))->get();
        }
        return view('books.index')->withBooks($books)->withCategories($categories);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('books.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        \Illuminate\Support\Facades\Validator::make($request->all(), [
            "title" => "required|min:5|max:200",
            "description" => "required|min:20|max:1000",
            "author" => "required|min:3|max:100",
            "publisher" => "required|min:3|max:200",
            "price" => "required|digits_between:0,10",
            "stock" => "required|digits_between:0,10",
            "cover" => "required"
        ])->validate();
        $newBook = new Book();
        $newBook->title = $request->title;
        $newBook->slug = Str::slug($request->title, '-');
        $newBook->description = $request->description;
        $newBook->author = $request->author;
        $newBook->price = $request->price;
        $newBook->publisher = $request->publisher;
        $newBook->stock = $request->stock;
        $newBook->status = $request->save_action;
        if ($request->hasFile('cover')) {
            $cover = $request->file('cover');
            $cover_name = $request->title . '-' . $cover->getClientOriginalName();
            $cover->move('cover-books/', $cover_name);
            $newBook->cover = $cover_name;
        }
        $newBook->created_by = Auth::user()->id;
        $newBook->save();

        if ($request->save_action == 'PUBLISH') {
            return redirect()->route('books.create')->with('status', 'Book successfully saved and published');
        } else {
            return redirect()->route('books.create')->with('status', 'Book saved as draft');
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($slug)
    {
        $book = Book::find($slug);
        return view('books.show')->withBook($book);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $book = Book::find($id);
        $categories = Category::all();
        return view('books.edit')->withBook($book)->withCategories($categories);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $book = Book::find($id);
        $book->title = $request->title;
        $book->slug = Str::slug($request->title, '-');
        $book->description = $request->description;
        $book->author = $request->author;
        $book->publisher = $request->publisher;
        $book->price = $request->price;
        $book->stock = $request->stock;
        $book->status = $request->status;
        $book->updated_by = Auth::user()->id;
        if ($request->hasFile('cover')) {
            if ($request->cover && file_exists(public_path('cover-books') . $book->cover)) {
                File::delete(public_path('cover-books/') . $book->cover);
            }

            $cover = $request->file('cover');
            $cover_name = $request->title . '-' . $cover->getClientOriginalName();
            $cover->move('cover-books', $cover_name);
        }

        $book->save();

        $book->categories()->sync($request->categories);
        return redirect()->route('books.index')->with('status', 'Book successfully updated');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $category = Book::find($id);
        $category->deleted_by = Auth::user()->id;
        $category->status = "DRAFT";
        $category->save();
        $category->delete();
        return redirect()->route('books.index')->with('status', 'Book successfully deleted');
    }

    public function trash(Request $request)
    {
        $books = Book::onlyTrashed()->get();
        if ($request->get('book_title')) {
            $books = Book::where('name', 'like',  "%$request->book_title%")->get();
        }
        return view('books.trash')->withBooks($books);
    }

    public function draft(Request $request)
    {
        $books = Book::where('status', 'DRAFT')->get();
        if ($request->get('book_title')) {
            $books = Book::where('name', 'like',  "%$request->book_title%")->get();
        }
        return view('books.draft')->withBooks($books);
    }

    public function restore($id)
    {
        $book = Book::withTrashed()->find($id);
        if ($book->trashed()) {
            $book->restore();
        } else {
            return redirect()->route('books.index')->with('status', 'Book is not in trash');
        }

        return redirect()->route('books.index')->with('status', 'Book successfully restored');
    }

    public function permanentDelete($id)
    {
        $book = Book::withTrashed()->find($id);
        if ($book->trashed()) {
            $book->forceDelete();
        }
        return redirect()->route('books.index')->with('status', 'Book Permanently Deleted');
    }

    public function homePages()
    {
        $categories =  Category::all();
        $books = Book::all();
        return view('frontend.layouts.home-page')->withCategories($categories)->withBooks($books);
    }

    public function order(Request $request, $books)
    {
        $book = Book::where('slug', $books)->first();
        if ($book->stock < $request->quantity) {
            return redirect()->back()->with('status', 'Jumlah pembelian lebih banyak dari pada stock');
        } else {
            $newOrder = new Order;
            $newOrder->user_id = Auth::user()->id;
            $newOrder->total_price = ($request->quantity * $book->price);
            $newOrder->invoice_number = rand(1, null) . date('dhs');
            $newOrder->status = 'SUBMIT';
            $newOrder->save();
            $bookOrder = Order::find($newOrder->id);
            $book->orders()->attach($bookOrder, ['quantity' => $request->quantity]);
            if ($newOrder) {
                $book->update([
                    'stock' => $book->stock - $request->quantity
                ]);
            }
            return redirect()->back()->with('status', 'Pembelian berhasil di proses');
        }
    }
}

resources/views/books/create.blade.php
@extends('layouts.app')

@section('title')
    Create Category
@endsection

@section('content')
    <div class="container-fluid">
        <div class="card">
            <div class="card-header">
                Create Book
            </div>
            <div class="row justify-content-center">
                <div class="col-md-8 shadow-sm p-5 m-2">
                    @if (session('status'))
                        <div class="alert alert-success">{{ session('status') }}</div>
                    @endif
                    <form action="{{ route('books.store') }}" method="post" enctype="multipart/form-data">
                        @csrf
                        <div class="form-group">
                            <label for="category_name">Title</label>
                            <input type="text" class="form-control {{ $errors->first('title') ? 'is-invalid' : '' }}" placeholder="Book Title" name="title" value="{{ old('title') }}">
                            <div class="invalid-feedback">
                                {{ $errors->first('title') }}
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="customFile">Cover</label>
                            <div class="custom-file">
                                <input type="file" name="cover" class="custom-file-input {{ $errors->first('cover') }}" id="customFile">
                                <label class="custom-file-label" for="customFile">Pilih Gambar</label>
                              </div>
                            <div class="invalid-feedback">
                                {{ $errors->first('cover') }}
                            </div>
                        </div>

                        <div class="form-group">
                            <label for="">Deskription</label>
                            <textarea name="description" id="description" cols="30" rows="6" class="form-control {{ $errors->has('desciption') ? 'is-invalid' : '' }}">{{ old('description') }}</textarea>
                            <div class="invalid-feedback">
                                {{ $errors->first('description') }}
                            </div>
                        </div>

                        <div class="form-group">
                            <label for="">Stock</label>
                            <input type="number" name="stock" id="stock" class="form-control {{ $errors->first('stock') }}" placeholder="Stock" value="{{ old('stock') }}">

                            <div class="invalid-feedback">
                                {{ $errors->first('stock') }}
                            </div>

                        </div>
                        <div class="form-group">
                            <label for="">Author</label>
                            <input type="text" class="form-control" name="author" placeholder="Author name">
                            <div class="invalid-feedback">
                                {{ $errors->first('author') }}
                            </div>
                        </div>

                        <div class="form-group">
                            <label for="">Publisher</label>
                            <input type="text" class="form-control" placeholder="Book Publisher" value="{{ old('publisher') }}" name="publisher">
                            <div class="invalid-feedback">
                                {{ $errors->first('publisher') }}
                            </div>
                        </div>

                        <div class="form-group">
                            <label for="price">Price</label>
                            <input type="number" name="price" id="price" value="{{ old('price') }}" class="form-control" placeholder="Book price">
                            <div class="invalid-feedback">
                                {{ $errors->first('price') }}
                            </div>
                        </div>


                        <div class="form-group">
                            <button name="save_action" value="PUBLISH" class="btn btn-info"><i class="fa fa-paper-plane mr-1"></i>Publish</button>
                            <button name="save_action" value="DRAFT" class="btn btn-warning"><i class="fa fa-bookmark mr-1"></i>Save as draft</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/books/edit.blade.php
@extends('layouts.app')

@section('title')
    Create Category
@endsection

@section('content')
    <div class="container-fluid">
        <div class="card">
            <div class="card-header">
                Create Book
            </div>
            <div class="row justify-content-center">
                <div class="col-md-8 shadow-sm p-5 m-2">
                    @if (session('status'))
                        <div class="alert alert-success">{{ session('status') }}</div>
                    @endif
                    <form action="{{ route('books.update' , $book->id) }}" method="post" enctype="multipart/form-data">
                        @csrf
                        @method('PUT')

                        <div class="form-group">
                            <label for="title">Title</label>
                            <input type="text" class="form-control" placeholder="Book Title" name="title" value="{{ $book->title }}">
                        </div>
                        <div class="form-group">
                            @if ($book->cover)
                                <img src="{{ asset('cover-books/') . '/' . $book->cover }}" alt="" class="img-thumbnail mx-auto d-block">
                            @endif
                            <label for="customFile">Cover</label>
                            <div class="custom-file">
                                <input type="file" name="cover" class="custom-file-input" id="customFile">
                                <label class="custom-file-label" for="customFile">Pilih Gambar</label>
                              </div>
                        </div>

                        <div class="form-group">
                            <label for="">Deskription</label>
                            <textarea name="description" id="description" cols="30" rows="6" class="form-control">{{ $book->description }}</textarea>
                        </div>

                        <div class="form-group">
                            <label for="">Stock</label>
                            <input type="number" name="stock" id="stock" class="form-control" placeholder="Stock" value="{{ $book->stock }}">
                        </div>
                        <div class="form-group">
                            <label for="">Author</label>
                            <input type="text" class="form-control" value="{{ $book->author }}" name="author" placeholder="Author name">
                        </div>

                        <div class="form-group">
                            <label for="">Publisher</label>
                            <input type="text" class="form-control" placeholder="Book Publisher" value="{{ $book->publisher }}" name="publisher">
                        </div>

                        <div class="form-group">
                            <label for="price">Price</label>
                            <input type="number" name="price" id="price" value="{{ $book->price }}" class="form-control" placeholder="Book price">
                        </div>

                        <div class="form-group">
                            <label for="status">Status</label>
                            <select class="form-control" name="status" id="status">
                                <option>-- Select --</option>
                                <option value="PUBLISH" {{ $book->status == 'PUBLISH' ? 'selected' : '' }}>Publish</option>
                                <option value="DRAFT" {{ $book->status == 'DRAFT' ? 'selected' : '' }}>Draft</option>
                            </select>
                        </div>

                        <div class="form-group">
                            <label>Category</label>
                            <div class="select2-purple">
                              <select class="select2" multiple="multiple" data-placeholder="Select Category" data-dropdown-css-class="select2-purple" name="categories[]" style="width: 100%;">
                                @foreach ($categories as $category)
                                    <option value="{{ $category->id }}">{{ $category->name }}</option>
                                @endforeach
                              </select>
                            </div>
                        </div>

                        <button class="btn-primary btn"><i class="fa fa-save mr-1"></i>Update</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection
@section('css-plugin')
  <!-- Select2 -->
  <link rel="stylesheet" href="{{ url('/') }}/plugins/select2/css/select2.min.css">
  <link rel="stylesheet" href="{{ url('/') }}/plugins/select2-bootstrap4-theme/select2-bootstrap4.min.css">
@endsection

@section('js-plugin')
<script src="{{ url('/') }}/plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
<script src="{{ url('/') }}/plugins/select2/js/select2.full.min.js"></script>
<script>
     //Initialize Select2 Elements
     $('.select2').select2()

    //Initialize Select2 Elements
    $('.select2bs4').select2({
    theme: 'bootstrap4'
    })
</script>
@endsection

resources/views/books/index.blade.php
@extends('layouts.app')

@section('title')
    List Book
@endsection

@section('content')
    <div class="container-fluid">
        <div class="card list-book">
            <div class="card-header">
                <div class="card-title">
                    List Book
                </div>
                <div class="card-tools">
                    <div class="row">
                        <form action="{{ route('books.index') }}" class="form-inline">
                            @csrf
                            <div class="input-group input-group-sm">
                                <input placeholder="Filter by title" value="{{ Request::get('title') }}" type="text" class="form-control" name="title">
                                <span class="input-group-append">
                                  <button type="submit" class="btn btn-info btn-flat"><i class="fa fa-filter"></i></button>
                                </span>
                              </div>
                        </form>
                        <a href="{{ route('books.index', ['status' => 'publish']) }}" class="m-1">
                            <button class="btn btn-outline-info btn-sm "><i class="fa fa-paper-plane mr-1"></i>All</button>
                        </a>
                        <a href="{{ route('books.index', ['status' => 'draft']) }}" class="m-1">
                            <button class="btn btn-outline-warning btn-sm "><i class="fa fa-bookmark mr-1"></i>Draft</button>
                        </a>
                        <a href="{{ route('books.trash') }}" class="m-1">
                            <button class="btn btn-outline-danger btn-sm "><i class="fa fa-bookmark mr-1"></i>Trashed</button>
                        </a>
                    </div>
                </div>
            </div>
            <div class="card-body">
                @if (session('status'))
                    <div class="alert alert-success">{{ session('status') }}</div>
                @endif
                <table id="example2" class="table table-sm table-bordered table-striped table-hover">
                    <thead>
                    <tr>
                      <th>Cover</th>
                      <th>Title</th>
                      <th>Author</th>
                      <th>Status</th>
                      <th>Categories</th>
                      <th>Stock</th>
                      <th>Price</th>
                      <th>Action</th>
                    </tr>
                    </thead>
                    <tbody>
                    @foreach ($books as $key => $book)
                    <tr>
                        <td><img src="{{ url('/') . '/cover-books/' . $book->cover }}" alt="" width="50px""></td>
                        <td>{!! $book->title !!}
                        <td>{{ $book->author }}</td>
                        <td>
                            @if ($book->status == 'PUBLISH')
                                <div class="badge badge-success">{{ $book->status }}</div>
                            @else
                                <div class="badge badge-warning">{{ $book->status }}</div>
                            @endif
                        </td>
                        <td>
                            @foreach ($book->categories as $category)
                                <div class="badge badge-light mb-1 d-block">
                                    {{ $category->name }}
                                </div>
                            @endforeach
                        </td>
                        <td>{{ $book->stock }}</td>
                        <td>Rp. {{ number_format($book->price, 2 , ',', '.') }}</td>
                        <td class="text-center">
                            <a href="{{ route('books.edit', $book->id) }}" class="btn btn-info btn-sm"><i class="fa fa-pencil-alt"></i></a>
                            <form onsubmit="return confirm('Delete this user permanently?')"
                                class="d-inline" action="{{route('books.destroy', $book->id)}}" method="POST">
                                @csrf
                                @method('DELETE')
                                <button class="btn btn-danger btn-sm" type="submit"><i class="fa fa-trash-alt "></i></button>
                            </form>
                            <a href="{{ route('categories.show', [$book->id]) }}" class="btn btn-success btn-sm">
                                <i class="fa fa-eye"></i>
                            </a>
                        </td>
                      </tr>
                    @endforeach
                    </tbody>
                  </table>
            </div>
        </div>
    </div>
@endsection

@section('js-plugin')
<script src="{{ url('/') }}/plugins/datatables/jquery.dataTables.min.js"></script>
<script src="{{ url('/') }}/plugins/datatables-bs4/js/dataTables.bootstrap4.min.js"></script>
<script src="{{ url('/') }}/plugins/datatables-responsive/js/dataTables.responsive.min.js"></script>
<script src="{{ url('/') }}/plugins/datatables-responsive/js/responsive.bootstrap4.min.js"></script>
<script>
    $(function () {
      $('#example2').DataTable({
        "paging": true,
        "lengthChange": false,
        "searching": false,
        "ordering": true,
        "info": true,
        "autoWidth": false,
        "responsive": true,
      });
    });
  </script>
@endsection

@section('css-plugin')
<link rel="stylesheet" href="{{ url('/') }}/plugins/datatables-bs4/css/dataTables.bootstrap4.min.css">
<link rel="stylesheet" href="{{ url('/') }}/plugins/datatables-responsive/css/responsive.bootstrap4.min.css">
@endsection

resources/views/books/trash.blade.php
@extends('layouts.app')

@section('title')
    List Book
@endsection

@section('content')
    <div class="container-fluid">
        <div class="card list-book">
            <div class="card-header">
                <div class="card-title">
                    List Book
                </div>
                <div class="card-tools">
                    <div class="row">
                        <form action="{{ route('books.index') }}" class="form-inline">
                            @csrf
                            <div class="input-group input-group-sm">
                                <input placeholder="Filter by title" value="{{ Request::get('book_title') }}" type="text" class="form-control" name="title">
                                <span class="input-group-append">
                                  <button type="submit" class="btn btn-info btn-flat"><i class="fa fa-filter"></i></button>
                                </span>
                              </div>
                        </form>
                        <a href="{{ route('books.index') }}" class="m-1">
                            <button class="btn btn-outline-primary btn-sm "><i class="fa fa-paper-plane mr-1"></i>All</button>
                        </a>
                        <a href="{{ route('books.draft') }}" class="m-1">
                            <button class="btn btn-outline-warning btn-sm "><i class="fa fa-bookmark mr-1"></i>Draft</button>
                        </a>
                        <a href="{{ route('books.trash') }}" class="m-1">
                            <button class="btn btn-outline-danger btn-sm "><i class="fa fa-bookmark mr-1"></i>Trashed</button>
                        </a>
                    </div>
                </div>
            </div>
            <div class="card-body">
                @if (session('status'))
                    <div class="alert alert-success">{{ session('status') }}</div>
                @endif
                <table id="example2" class="table table-sm table-bordered table-striped table-hover">
                    <thead>
                    <tr>
                      <th>Cover</th>
                      <th>Title</th>
                      <th>Author</th>
                      <th>Status</th>
                      <th>Categories</th>
                      <th>Stock</th>
                      <th>Price</th>
                      <th>Action</th>
                    </tr>
                    </thead>
                    <tbody>
                    @foreach ($books as $key => $book)
                    <tr>
                        <td><img src="{{ url('/') . '/cover-books/' . $book->cover }}" alt="" width="50px""></td>
                        <td>{!! $book->title !!}
                        <td>{{ $book->author }}</td>
                        <td>
                            @if ($book->status == 'PUBLISH')
                                <div class="badge badge-success">{{ $book->status }}</div>
                            @else
                                <div class="badge badge-warning">{{ $book->status }}</div>
                            @endif
                        </td>
                        <td>
                            @foreach ($book->categories as $category)
                                <div class="badge badge-light mb-1 d-block">
                                    {{ $category->name }}
                                </div>
                            @endforeach
                        </td>
                        <td>{{ $book->stock }}</td>
                        <td>IDR {{  number_format($book->price, 0 , ',', '.') }}</td>
                        <td class="text-center">
                            <a href="{{ route('books.restore', $book->id) }}" class="btn btn-info btn-sm"><i class="fa fa-undo"></i></a>
                            <form onsubmit="return confirm('Delete this user permanently?')"
                                class="d-inline" action="{{route('books.permanent', $book->id)}}" method="POST">
                                @csrf
                                @method('DELETE')
                                <button class="btn btn-danger btn-sm" type="submit"><i class="fa fa-trash-alt "></i></button>
                            </form>
                        </td>
                      </tr>
                    @endforeach
                    </tbody>
                  </table>
            </div>
        </div>
    </div>
@endsection

@section('js-plugin')
<script src="{{ url('/') }}/plugins/datatables/jquery.dataTables.min.js"></script>
<script src="{{ url('/') }}/plugins/datatables-bs4/js/dataTables.bootstrap4.min.js"></script>
<script src="{{ url('/') }}/plugins/datatables-responsive/js/dataTables.responsive.min.js"></script>
<script src="{{ url('/') }}/plugins/datatables-responsive/js/responsive.bootstrap4.min.js"></script>
<script>
    $(function () {
      $('#example2').DataTable({
        "paging": true,
        "lengthChange": false,
        "searching": false,
        "ordering": true,
        "info": true,
        "autoWidth": false,
        "responsive": true,
      });
    });
  </script>
@endsection

@section('css-plugin')
<link rel="stylesheet" href="{{ url('/') }}/plugins/datatables-bs4/css/dataTables.bootstrap4.min.css">
<link rel="stylesheet" href="{{ url('/') }}/plugins/datatables-responsive/css/responsive.bootstrap4.min.css">
@endsection