routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/



Route::post('users/register-user', 'UserController@registerUser')->name('users.register');
Route::resource('users', 'UserController');

Route::delete('/categories/{categories}/permanent', 'CategoryController@permanentDelete')->name('categories.permanent');
Route::get('/categories/{categories}/restore', 'CategoryController@restore')->name('categories.restore');
Route::get('/categories/trash', 'CategoryController@trash')->name('categories.trash');
Route::resource('categories', 'CategoryController');

Route::get('/', 'BookController@homePages');
Route::delete('/books/{books}/permanent', 'BookController@permanentDelete')->name('books.permanent');
Route::get('/books/{books}/restore', 'BookController@restore')->name('books.restore');
Route::get('/books/trash', 'BookController@trash')->name('books.trash');
Route::get('/books/draft', 'BookController@draft')->name('books.draft');
Route::put('/books/order/{books}', 'BookController@order')->name('books.order');
Route::resource('books', 'BookController');

Route::delete('/orders/{orders}/permanent', 'OrderController@permanentDelete')->name('orders.permanent');
Route::get('/orders/{orders}/restore', 'OrderController@restore')->name('orders.restore');
Route::get('/orders/trash', 'OrderController@trash')->name('orders.trash');
Route::resource('orders', 'OrderController');
Auth::routes();
Route::get('/home', 'HomeController@index')->name('home');

app/Models/Category.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use App\Models\Book;

class Category extends Model
{
    use SoftDeletes;

    public function books()
    {
        return $this->belongsToMany(Book::class);
    }
}

app/Http/Controllers/CategoryController.php
<?php

namespace App\Http\Controllers;

use App\Models\Category;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\File;
use Illuminate\Support\Facades\Gate;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Facades\Validator;
use Illuminate\Support\Str;

class CategoryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function __construct()
    {
        $this->middleware(function ($request, $next) {
            if (Gate::allows('manage-categories')) {
                return $next($request);
            }
            abort(403, 'Anda tidak memiliki akses untuk mengakses halaman ini');
        });
    }
    public function index(Request $request)
    {
        $categories = Category::all();
        if ($request->get('category_name')) {
            $categories = Category::where('name', 'like',  "%$request->category_name%")->get();
        }

        return view('categories.index')->withCategories($categories);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('categories.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        Validator::make($request->all(), [
            'category_name' => 'required',
            'category_image' => 'required'
        ])->validate();
        $newCategory = new Category();
        $newCategory->name = $request->get('category_name');
        if ($request->hasFile('category_image')) {
            $category_image = $request->file('category_image');
            $image_name = $request->get('category_name') . $category_image->getClientOriginalName();
            $category_image->move('categories-images', $image_name);
            $newCategory->image = $image_name;
        }
        $newCategory->created_by = Auth::user()->id;
        $newCategory->slug = Str::slug($request->get('category_name'), '-');
        $newCategory->save();
        return redirect()->route('categories.create')->with(
            'status',
            'Category successfully created'
        );
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $category = Category::find($id);
        return view('categories.edit')->withCategory($category);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $category = Category::find($id);

        $category->name = $request->get('category_name');
        $category->slug = Str::slug($request->get('category_name', '-'));
        if ($request->hasFile('category_image')) {
            if ($category->image && file_exists(public_path('categories-images/' . $category->image))) {
                File::delete(public_path('categories-images/' . $category->image));
            }

            $category_image = $request->file('category_image');
            $image_name = $request->get('category_name') . $category_image->getClientOriginalName();
            $category_image->move('categories-images', $image_name);
            $category->image = $image_name;
        }
        $category->updated_by = Auth::user()->id;


        $category->save();
        return redirect()->route('categories.edit', $id)->with('status', 'Category was updated');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $category = Category::find($id);
        $category->deleted_by = Auth::user()->id;
        $category->delete();
        $category->save();
        return redirect()->route('categories.index')->with('status', 'Category successfully deleted');
    }

    public function trash(Request $request)
    {
        $categories = Category::onlyTrashed()->get();
        if ($request->get('category_name')) {
            $categories = Category::where('name', 'like',  "%$request->category_name%")->get();
        }
        return view('categories.trash')->withCategories($categories);
    }

    public function restore($id)
    {
        $category = Category::withTrashed()->find($id);
        if ($category->trashed()) {
            $category->restore();
        } else {
            return redirect()->route('categories.index')->with('status', 'Category is not in trash');
        }

        return redirect()->route('categories.index')->with('status', 'Category successfully restored');
    }

    public function permanentDelete($id)
    {
        $category = Category::withTrashed()->find($id);
        if ($category->trashed()) {
            $category->forceDelete();
        }
        return redirect()->route('categories.index')->with('status', 'Category Permanently Deleted');
    }
}

resources/views/categories/create.blade.php
@extends('layouts.app')

@section('title')
    Create Category
@endsection

@section('content')
    <div class="container-fluid">
        <div class="card">
            <div class="row justify-content-center">
                <div class="col-md-8 shadow-sm p-5 m-5">
                    @if (session('status'))
                        <div class="alert alert-success">{{ session('status') }}</div>
                    @endif
                    <form action="{{ route('categories.store') }}" method="post" enctype="multipart/form-data">
                        @csrf
                        <div class="form-group">
                            <label for="category_name">Category Name</label>
                            <input type="text" class="form-control {{ $errors->first('category_name') ? 'is-invalid' : '' }}" placeholder="Category Name" name="category_name" value="{{ old('category_name') }}">
                            <div class="invalid-feedback">
                                {{ $errors->first('category_name') }}
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="customFile">Category Image</label>
                            <div class="custom-file">
                                <input type="file" name="category_image" class="custom-file-input {{ $errors->first('category_image') ? 'is-invalid' : '' }}" id="customFile">
                                <label class="custom-file-label" for="customFile">Pilih Gambar</label>
                              </div>
                              <div class="invalid-feedback">
                                {{ $errors->first('category_image') }}
                             </div>
                        </div>

                        <div class="form-group">
                            <button class="btn btn-primary btn-block"><i class="fa fa-save mr-1"></i>Save Category</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/categories/edit.blade.php
@extends('layouts.app')

@section('title')
    Create Category
@endsection

@section('content')
    <div class="container-fluid">
        <div class="card">
            <div class="row justify-content-center">
                <div class="col-md-8 shadow-sm p-5 m-5">
                    @if (session('status'))
                        <div class="alert alert-success">{{ session('status') }}</div>
                    @endif
                    <form action="{{ route('categories.update', $category->id) }}" method="post" enctype="multipart/form-data">
                        @method('PUT')
                        @csrf
                        <div class="form-group">
                            <label for="category_name">Category Name</label>
                            <input type="text" class="form-control" placeholder="Category Name" name="category_name" value="{{ $category->name }}">
                        </div>

                        <div class="form-group">
                            @if ($category->image)
                            <img src="{{ asset('/') . 'categories-images/' . $category->image }}" alt="" class="img-thumbnail mx-auto d-block">
                            @else
                            Tidak ada gambar
                            @endif
                            <label for="customFile">Category Image</label>
                            <div class="custom-file">
                                <input type="file" name="category_image" class="custom-file-input" id="customFile">
                                <label class="custom-file-label" for="customFile">Pilih Gambar</label>
                              </div>
                        </div>

                        <div class="form-group">
                            <button class="btn btn-primary btn-block"><i class="fa fa-save mr-1"></i>Save Category</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/categories/index.blade.php
@extends('layouts.app')

@section('title')
    List Category
@endsection

@section('content')
    <div class="container-fluid">
        <div class="card list-category">
            <div class="card-header">
                <div class="card-title">
                    List Category
                </div>
                <div class="card-tools">
                    <div class="row">
                        <form action="{{ route('categories.index') }}" class="form-inline">
                            @csrf
                            <div class="input-group input-group-sm">
                                <input type="text" name="category_name" value="{{ Request::get('category_name') }}" class="form-control">
                                <span class="input-group-append">
                                  <button type="submit" class="btn btn-info btn-flat">Filter</button>
                                </span>
                              </div>
                        </form>
                        <a href="{{ route('categories.index') }}" class="m-1">
                            <button class="btn btn-outline-info btn-sm "><i class="fa fa-paper-plane"></i> Published</button>
                        </a>
                        <a href="{{ route('categories.trash') }}" class="m-1">
                            <button class="btn btn-outline-danger btn-sm "><i class="fa fa-trash-alt"></i>Trash</button>
                        </a>
                    </div>
                </div>
            </div>
            <div class="card-body">
                @if (session('status'))
                    <div class="alert alert-success">{{ session('status') }}</div>
                @endif
                <table id="example2" class="table table-sm table-bordered table-striped table-hover">
                    <thead>
                    <tr>
                      <th>No.</th>
                      <th>Name</th>
                      <th>Slug</th>
                      <th>Image</th>
                      <th>Options</th>
                    </tr>
                    </thead>
                    <tbody>
                    @foreach ($categories as $key => $category)
                    <tr>
                        <td>{{ $key + 1 }}</td>
                        <td>{!! $category->name !!}
                        <td><small>{!!  url('/') . '/' .$category->slug !!}</small>
                        </td>
                        <td><img src="{{ url('/') . '/categories-images/' . $category->image }}" alt="" width="50px""></td>
                        <td class="text-center">
                            <a href="{{ route('categories.edit', $category->id) }}" class="btn btn-info btn-sm"><i class="fa fa-pencil-alt"></i></a>
                            <form onsubmit="return confirm('Delete this user permanently?')"
                                class="d-inline" action="{{route('categories.destroy', $category->id)}}" method="POST">
                                @csrf
                                @method('DELETE')
                                <button class="btn btn-danger btn-sm" type="submit"><i class="fa fa-trash-alt "></i></button>
                            </form>
                            <a href="{{ route('categories.show', [$category->id]) }}" class="btn btn-success btn-sm">
                                <i class="fa fa-eye"></i>
                            </a>
                        </td>
                      </tr>
                    @endforeach
                    </tbody>
                  </table>
            </div>
        </div>
    </div>
@endsection

@section('js-plugin')
<script src="{{ url('/') }}/plugins/datatables/jquery.dataTables.min.js"></script>
<script src="{{ url('/') }}/plugins/datatables-bs4/js/dataTables.bootstrap4.min.js"></script>
<script src="{{ url('/') }}/plugins/datatables-responsive/js/dataTables.responsive.min.js"></script>
<script src="{{ url('/') }}/plugins/datatables-responsive/js/responsive.bootstrap4.min.js"></script>
<script>
    $(function () {
      $('#example2').DataTable({
        "paging": true,
        "lengthChange": false,
        "searching": false,
        "ordering": true,
        "info": true,
        "autoWidth": false,
        "responsive": true,
      });
    });
  </script>
@endsection

@section('css-plugin')
<link rel="stylesheet" href="{{ url('/') }}/plugins/datatables-bs4/css/dataTables.bootstrap4.min.css">
<link rel="stylesheet" href="{{ url('/') }}/plugins/datatables-responsive/css/responsive.bootstrap4.min.css">
@endsection

resources/views/categories/trash.blade.php
@extends('layouts.app')

@section('title')
    Trashed Category
@endsection

@section('content')
    <div class="container-fluid">
        <div class="card list-category">
            <div class="card-header">
                <div class="card-title">
                    Trashed Category
                </div>
                <div class="card-tools">
                    <div class="row">
                        <form action="{{ route('categories.index') }}" class="form-inline">
                            @csrf
                            <div class="input-group input-group-sm">
                                <input type="text" name="category_name" value="{{ Request::get('category_name') }}" class="form-control">
                                <span class="input-group-append">
                                  <button type="submit" class="btn btn-info btn-flat">Filter</button>
                                </span>
                              </div>
                        </form>
                        <a href="{{ route('categories.index') }}" class="m-1">
                            <button class="btn btn-outline-info btn-sm "><i class="fa fa-paper-plane"></i> Published</button>
                        </a>
                        <a href="{{ route('categories.trash') }}" class="m-1">
                            <button class="btn btn-outline-danger btn-sm "><i class="fa fa-trash-alt"></i>Trash</button>
                        </a>
                    </div>
                </div>
            </div>
            <div class="card-body">
                @if (session('status'))
                    <div class="alert alert-success">{{ session('status') }}</div>
                @endif
                <table id="example2" class="table table-sm table-bordered table-striped table-hover">
                    <thead>
                    <tr>
                      <th>No.</th>
                      <th>Name</th>
                      <th>Slug</th>
                      <th>Image</th>
                      <th>Options</th>
                    </tr>
                    </thead>
                    <tbody>
                    @foreach ($categories as $key => $category)
                    <tr>
                        <td>{{ $key + 1 }}</td>
                        <td>{!! $category->name !!}
                        <td><small>{!!  url('/') . '/' .$category->slug !!}</small>
                        </td>
                        <td><img src="{{ url('/') . '/categories-images/' . $category->image }}" alt="" width="50px""></td>
                        <td class="text-center">
                            <a href="{{ route('categories.restore', $category->id) }}" class="btn btn-info btn-sm"><i class="fa fa-undo"></i></a>
                            <form onsubmit="return confirm('Delete this user permanently?')"
                                class="d-inline" action="{{route('categories.permanent', $category->id)}}" method="POST">
                                @csrf
                                @method('DELETE')
                                <button class="btn btn-danger btn-sm" type="submit"><i class="fa fa-trash-alt "></i></button>
                            </form>
                        </td>
                      </tr>
                    @endforeach
                    </tbody>
                  </table>
            </div>
        </div>
    </div>
@endsection

@section('js-plugin')
<script src="{{ url('/') }}/plugins/datatables/jquery.dataTables.min.js"></script>
<script src="{{ url('/') }}/plugins/datatables-bs4/js/dataTables.bootstrap4.min.js"></script>
<script src="{{ url('/') }}/plugins/datatables-responsive/js/dataTables.responsive.min.js"></script>
<script src="{{ url('/') }}/plugins/datatables-responsive/js/responsive.bootstrap4.min.js"></script>
<script>
    $(function () {
      $('#example2').DataTable({
        "paging": true,
        "lengthChange": false,
        "searching": false,
        "ordering": true,
        "info": true,
        "autoWidth": false,
        "responsive": true,
      });
    });
  </script>
@endsection

@section('css-plugin')
<link rel="stylesheet" href="{{ url('/') }}/plugins/datatables-bs4/css/dataTables.bootstrap4.min.css">
<link rel="stylesheet" href="{{ url('/') }}/plugins/datatables-responsive/css/responsive.bootstrap4.min.css">
@endsection