routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/



Route::post('users/register-user', 'UserController@registerUser')->name('users.register');
Route::resource('users', 'UserController');

Route::delete('/categories/{categories}/permanent', 'CategoryController@permanentDelete')->name('categories.permanent');
Route::get('/categories/{categories}/restore', 'CategoryController@restore')->name('categories.restore');
Route::get('/categories/trash', 'CategoryController@trash')->name('categories.trash');
Route::resource('categories', 'CategoryController');

Route::get('/', 'BookController@homePages');
Route::delete('/books/{books}/permanent', 'BookController@permanentDelete')->name('books.permanent');
Route::get('/books/{books}/restore', 'BookController@restore')->name('books.restore');
Route::get('/books/trash', 'BookController@trash')->name('books.trash');
Route::get('/books/draft', 'BookController@draft')->name('books.draft');
Route::put('/books/order/{books}', 'BookController@order')->name('books.order');
Route::resource('books', 'BookController');

Route::delete('/orders/{orders}/permanent', 'OrderController@permanentDelete')->name('orders.permanent');
Route::get('/orders/{orders}/restore', 'OrderController@restore')->name('orders.restore');
Route::get('/orders/trash', 'OrderController@trash')->name('orders.trash');
Route::resource('orders', 'OrderController');
Auth::routes();
Route::get('/home', 'HomeController@index')->name('home');

app/Models/Order.php
<?php

namespace App\Models;

use App\User;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use App\Models\Book;

class Order extends Model
{
    use SoftDeletes;

    public function user()
    {
        return $this->belongsTo(User::class);
    }

    public function books()
    {
        return $this->belongsToMany(Book::class)->withPivot('quantity');
    }

    public function getTotalQuantityAttribute()
    {
        $total_quantity  = 0;
        foreach ($this->books as  $book) {
            $total_quantity += $book->pivot->quantity;
        }

        return $total_quantity;
    }
}

app/Http/Controllers/OrderController.php
<?php

namespace App\Http\Controllers;

use App\Models\Book;
use App\Models\Order;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Gate;

class OrderController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function __construct()
    {
        $this->middleware(function ($request, $next) {
            if (Gate::allows('manage-orders')) {
                return $next($request);
            }
            abort(403, 'Anda tidak memiliki akses untuk mengakses halaman ini');
        });
    }
    public function index(Request $request)
    {
        $status = $request->status;
        $buyer_email = $request->buyer_email;
        $orders = Order::with('user')
            ->with('books')
            ->whereHas('user', function ($query) use ($buyer_email) {
                $query->where('email', 'LIKE', "%$buyer_email%");
            })
            ->where('status', 'LIKE', "%$status%")
            ->get();
        return view('orders.index')->withOrders($orders);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create(Request $request)
    {
        // dd($request->all());
        $book = Book::where('slug', $request->books)->first();
        return view('orders.create')->withBook($book);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Order  $order
     * @return \Illuminate\Http\Response
     */
    public function show(Order $order)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Order  $order
     * @return \Illuminate\Http\Response
     */
    public function edit(Order $order)
    {
        $order = Order::find($order->id);
        return view('orders.edit')->withOrder($order);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Order  $order
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Order $order)
    {
        $order = Order::find($order->id);
        $order->status = $request->status;
        $order->save();
        return redirect()->route('orders.edit', [$order->id])->with('status', 'Order status succesfully updated');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Order  $order
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $category = Order::find($id);
        $category->delete();
        return redirect()->route('orders.index')->with('status', 'Book successfully deleted');
    }

    public function trash(Request $request)
    {
        $order = Order::onlyTrashed()->get();
        return view('orders.trash')->withOrders($order);
    }


    public function restore($id)
    {
        $order = Order::withTrashed()->find($id);
        if ($order->trashed()) {
            $order->restore();
        } else {
            return redirect()->route('orders.index')->with('status', 'Book is not in trash');
        }

        return redirect()->route('orders.index')->with('status', 'Book successfully restored');
    }

    public function permanentDelete($id)
    {
        $order = Order::withTrashed()->find($id);
        if ($order->trashed()) {
            $order->forceDelete();
        }
        return redirect()->route('order.index')->with('status', 'Book Permanently Deleted');
    }
}

resources/views/orders/create.blade.php
@extends('frontend.layouts.app')

@section('content')
    <div class="container-fluid">
        <div class="row justify-content-center mt-5">
            <div class="col-md-8">
                @if (Session::get('status'))
                    <div class="alert alert-warning">
                        {{ Session::get('status') }}
                    </div>
                @endif
                <form action="{{ route('books.order', $book->slug) }}" method="post">
                    @csrf
                    @method('PUT')
                    <div class="card p-4">
                        <div class="row justify-content-center">
                            <div class="col-md-4">
                                {{-- {{ dd($book) }} --}}
                                <img src="{{ asset('cover-books') . '/' . $book->cover }}" alt="" class="img-thumbnail">
                            </div>
                            <div class="col-md-8">
                                <table class="table table-borderless table-sm">
                                    <tbody>
                                        <tr>
                                            <td scope="row">{{ ('Title') }}</td>
                                            <td>:</td>
                                            <td>{{ $book->title }}</td>
                                        </tr>
                                        <tr>
                                            <td scope="row">{{ ('Description') }}</td>
                                            <td>:</td>
                                            <td>{{ $book->description }}</td>
                                        </tr>
                                        <tr>
                                            <td scope="row">{{ ('Price') }}</td>
                                            <td>:</td>
                                            <td><b>IDR {{ number_format($book->price , 2 , ',', '.')}}</b></td>
                                        </tr>
                                        <tr>
                                            <td scope="row">{{ ('Stock') }}</td>
                                            <td>:</td>
                                            <td>{{ $book->stock }}</td>
                                        </tr>
                                        <tr>
                                            <div class="form-group-sm">
                                                <td scope="row">{{ ('Quantity') }}</td>
                                                <td>:</td>
                                                <td>
                                                    <input required type="number" name="quantity" id="quantity" class="form-control form-control-sm" placeholder="1" aria-describedby="helpId">
                                                </td>
                                            </div>

                                        </tr>
                                        <tr>
                                            <td colspan="3">
                                                <button class="btn-info btn btn-block" {{ $book->stock == 0 ? 'disabled' : '' }}>Order</button>
                                            </td>
                                        </tr>
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
@endsection

resources/views/orders/edit.blade.php
@extends('layouts.app')

@section('content')
    <div class="container-fluid">
        <div class="card">
            <div class="card-header">
                Create Book
            </div>
            <div class="row justify-content-center">
                <div class="col-md-8 shadow-sm p-5 m-2">
                    @if (session('status'))
                        <div class="alert alert-success">{{ session('status') }}</div>
                    @endif
                    <form action="{{ route('orders.update', $order->id) }}" method="post" enctype="multipart/form-data">
                        @csrf
                        @method('PUT')
                        <div class="form-group">
                            <label for="invoice_number">Invoice Number</label>
                            <input disabled type="text" class="form-control" name="invoice_number" value="{{ $order->invoice_number }}">
                        </div>

                        <div class="form-group">
                            <label for="Buyer">Buyer</label>
                            <input disabled type="text" class="form-control" name="buyer" value="{{ $order->user->name }}">
                        </div>

                        <div class="form-group">
                            <label for="created_at">Order Date</label>
                            <input type="text" class="form-control" name="created_at" disabled value="{{ $order->created_at }}">
                        </div>

                        <div class="form-group">
                            <label for="created_at">Books ({{ $order->totalQuantity }})</label>
                            @foreach ($order->books as $book)
                                <div class="inline-block">
                                    <button type="button" class="btn btn-light btn-sm">
                                        {{ $book->title }} <span class="badge badge-light">{{ $book->pivot->quantity }}</span>
                                      </button>
                                </div>
                            @endforeach
                        </div>

                        <div class="form-group">
                            <label for="">Total Price</label>
                            <input disabled type="text" class="form-control" value="{{ $order->total_price }}">
                        </div>

                        <div class="form-group">
                            <label for="status">Status</label><br>
                            <select class="form-control" name="status" id="status">
                                <option {{$order->status == "SUBMIT" ? "selected" : ""}}
                                value="SUBMIT">SUBMIT</option>
                                <option {{$order->status == "PROCESS" ? "selected" : ""}}
                                value="PROCESS">PROCESS</option>
                                <option {{$order->status == "FINISH" ? "selected" : ""}}
                                value="FINISH">FINISH</option>
                                <option {{$order->status == "CANCEL" ? "selected" : ""}}
                                value="CANCEL">CANCEL</option>
                            </select>
                        </div>




                        <button class="btn-primary btn"><i class="fa fa-save mr-1"></i>Update</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/orders/index.blade.php
@extends('layouts.app')

@section('title')
    List order
@endsection

@section('content')
    <div class="container-fluid">
        <div class="card list-category">
            <div class="card-header">
                <div class="card-title">
                    List Orders
                </div>
                <div class="card-tools">
                    <div class="row">
                        <form action="{{ route('orders.index') }}" class="form-inline">
                            @csrf
                            <div class="form-group input-group-sm">
                                <input type="email" class="form-control mr-2" name="email" placeholder="Filter by email" >
                            </div>
                            <div class="input-group input-group-sm">
                                <select name="status" class="form-control" id="status">
                                    <option value="">ANY</option>
                                    <option {{Request::get('status') == "SUBMIT" ? "selected" :""}} value="SUBMIT">SUBMIT</option>
                                    <option {{Request::get('status') == "PROCESS" ? "selected" : ""}} value="PROCESS">PROCESS</option>
                                    <option {{Request::get('status') == "FINISH" ? "selected" : ""}} value="FINISH">FINISH</option>
                                    <option {{Request::get('status') == "CANCEL" ? "selected" : ""}} value="CANCEL">CANCEL</option>
                                </select>
                                <span class="input-group-append">
                                  <button type="submit" class="btn btn-info btn-flat">Filter</button>
                                </span>
                              </div>
                              <a href="{{ route('orders.trash') }}" class="btn btn-danger btn-sm ml-1 mr-1"><i class="fa fa-trash"></i>Trash</a>
                        </form>
                    </div>
                </div>
            </div>
            <div class="card-body">
                @if (session('status'))
                    <div class="alert alert-success">{{ session('status') }}</div>
                @endif
                <table id="example2" class="table table-sm table-bordered table-striped table-hover">
                    <thead>
                    <tr>
                      <th>No.</th>
                      <th>Invoice Number</th>
                      <th>Status</th>
                      <th>Buyer</th>
                      <th>Total Quantity</th>
                      <th>Order Date</th>
                      <th>Total Price</th>
                      <th>Options</th>
                    </tr>
                    </thead>
                    <tbody>
                    @foreach ($orders as $key => $order)
                    <tr>
                        <td>{{ $key + 1 }}</td>
                        <td>{!! $order->invoice_number !!}
                        <td>
                            @if ($order->status == 'SUBMIT')
                                <div class="badge badge-warning">{{ $order->status }}</div>
                            @elseif($order->status == "PROSES")
                                 <div class="badge badge-info">{{ $order->status }}</div>
                            @elseif($order->status == "FINISH")
                                <div class="badge badge-success">{{ $order->status }}</div>
                            @else
                                <div class="badge badge-danger">{{ $order->status }}</div>
                            @endif
                        </td>
                        <td>{{ $order->user->name }} <br> <small>{{ $order->user->email  }}</small></td>
                        <td>{{ $order->totalQuantity}}</td>
                        <td>{{ $order->created_at}}</td>
                        <td>{{ $order->total_price}}</td>
                        <td class="text-center">
                            <a href="{{ route('orders.edit', $order->id) }}" class="btn btn-info btn-sm"><i class="fa fa-pencil-alt"></i></a>
                            <form onsubmit="return confirm('Delete this user permanently?')"
                                class="d-inline" action="{{route('orders.destroy', $order->id)}}" method="POST">
                                @csrf
                                @method('DELETE')
                                <button class="btn btn-danger btn-sm" type="submit"><i class="fa fa-trash-alt "></i></button>
                            </form>
                            <a href="{{ route('orders.show', [$order->id]) }}" class="btn btn-success btn-sm">
                                <i class="fa fa-eye"></i>
                            </a>
                        </td>
                      </tr>
                    @endforeach
                    </tbody>
                  </table>
            </div>
        </div>
    </div>
@endsection

@section('js-plugin')
<script src="{{ url('/') }}/plugins/datatables/jquery.dataTables.min.js"></script>
<script src="{{ url('/') }}/plugins/datatables-bs4/js/dataTables.bootstrap4.min.js"></script>
<script src="{{ url('/') }}/plugins/datatables-responsive/js/dataTables.responsive.min.js"></script>
<script src="{{ url('/') }}/plugins/datatables-responsive/js/responsive.bootstrap4.min.js"></script>
<script>
    $(function () {
      $('#example2').DataTable({
        "paging": true,
        "lengthChange": false,
        "searching": false,
        "ordering": true,
        "info": true,
        "autoWidth": false,
        "responsive": true,
      });
    });
  </script>
@endsection

@section('css-plugin')
<link rel="stylesheet" href="{{ url('/') }}/plugins/datatables-bs4/css/dataTables.bootstrap4.min.css">
<link rel="stylesheet" href="{{ url('/') }}/plugins/datatables-responsive/css/responsive.bootstrap4.min.css">
@endsection

resources/views/orders/trash.blade.php
@extends('layouts.app')

@section('title')
    List order
@endsection

@section('content')
    <div class="container-fluid">
        <div class="card list-category">
            <div class="card-header">
                <div class="card-title">
                    List Orders
                </div>
                <div class="card-tools">
                    <div class="row">
                        <form action="{{ route('orders.index') }}" class="form-inline">
                            @csrf
                            <div class="form-group input-group-sm">
                                <input type="email" class="form-control mr-2" name="email" placeholder="Filter by email" >
                            </div>
                            <div class="input-group input-group-sm">
                                <select name="status" class="form-control" id="status">
                                    <option value="">ANY</option>
                                    <option {{Request::get('status') == "SUBMIT" ? "selected" :""}} value="SUBMIT">SUBMIT</option>
                                    <option {{Request::get('status') == "PROCESS" ? "selected" : ""}} value="PROCESS">PROCESS</option>
                                    <option {{Request::get('status') == "FINISH" ? "selected" : ""}} value="FINISH">FINISH</option>
                                    <option {{Request::get('status') == "CANCEL" ? "selected" : ""}} value="CANCEL">CANCEL</option>
                                </select>
                                <span class="input-group-append">
                                  <button type="submit" class="btn btn-info btn-flat">Filter</button>
                                </span>
                              </div>
                              <a href="{{ route('orders.trash') }}" class="btn btn-danger btn-sm ml-1 mr-1"><i class="fa fa-trash"></i>Trash</a>
                        </form>
                    </div>
                </div>
            </div>
            <div class="card-body">
                @if (session('status'))
                    <div class="alert alert-success">{{ session('status') }}</div>
                @endif
                <table id="example2" class="table table-sm table-bordered table-striped table-hover">
                    <thead>
                    <tr>
                      <th>No.</th>
                      <th>Invoice Number</th>
                      <th>Status</th>
                      <th>Buyer</th>
                      <th>Total Quantity</th>
                      <th>Order Date</th>
                      <th>Total Price</th>
                      <th>Options</th>
                    </tr>
                    </thead>
                    <tbody>
                    @foreach ($orders as $key => $order)
                    <tr>
                        <td>{{ $key + 1 }}</td>
                        <td>{!! $order->invoice_number !!}
                        <td>
                            @if ($order->status == 'SUBMIT')
                                <div class="badge badge-warning">{{ $order->status }}</div>
                            @elseif($order->status == "PROSES")
                                 <div class="badge badge-info">{{ $order->status }}</div>
                            @elseif($order->status == "FINISH")
                                <div class="badge badge-success">{{ $order->status }}</div>
                            @else
                                <div class="badge badge-danger">{{ $order->status }}</div>
                            @endif
                        </td>
                        <td>{{ $order->user->name }} <br> <small>{{ $order->user->email  }}</small></td>
                        <td>{{ $order->totalQuantity}}</td>
                        <td>{{ $order->created_at}}</td>
                        <td>{{ $order->total_price}}</td>
                        <td class="text-center">
                            <a href="{{ route('orders.restore', $order->id) }}" class="btn btn-info btn-sm"><i class="fa fa-undo-alt"></i></a>
                            <form onsubmit="return confirm('Delete this user permanently?')"
                                class="d-inline" action="{{route('orders.permanent', $order->id)}}" method="POST">
                                @csrf
                                @method('DELETE')
                                <button class="btn btn-danger btn-sm" type="submit"><i class="fa fa-trash-alt "></i></button>
                            </form>
                        </td>
                      </tr>
                    @endforeach
                    </tbody>
                  </table>
            </div>
        </div>
    </div>
@endsection

@section('js-plugin')
<script src="{{ url('/') }}/plugins/datatables/jquery.dataTables.min.js"></script>
<script src="{{ url('/') }}/plugins/datatables-bs4/js/dataTables.bootstrap4.min.js"></script>
<script src="{{ url('/') }}/plugins/datatables-responsive/js/dataTables.responsive.min.js"></script>
<script src="{{ url('/') }}/plugins/datatables-responsive/js/responsive.bootstrap4.min.js"></script>
<script>
    $(function () {
      $('#example2').DataTable({
        "paging": true,
        "lengthChange": false,
        "searching": false,
        "ordering": true,
        "info": true,
        "autoWidth": false,
        "responsive": true,
      });
    });
  </script>
@endsection

@section('css-plugin')
<link rel="stylesheet" href="{{ url('/') }}/plugins/datatables-bs4/css/dataTables.bootstrap4.min.css">
<link rel="stylesheet" href="{{ url('/') }}/plugins/datatables-responsive/css/responsive.bootstrap4.min.css">
@endsection